# Differential Drive Controller Configurations

cmd_vel_publisher: "/cmd_vel"
odometry_subscriber: "/odom"

pid_velocity_controller_gain:
  p: 0.0
  i: 0.0
  d: 0.0

# Turtlebot3 Burger parameters 
limits:
  linear:
    x:
      max_velocity           : 0.2   # m/s
  angular:
    z:
      max_velocity           : 2.84   # rad/s

target_pose:
  x: 2.0
  y: 3.3
